= HTTP Source

A simple implementation of an _http source_, accepting POST requests
and sending messages to output stream(s) configured _via_ environment variables.

== Building
Having a working go 1.13+ installation and ko[https://github.com/google/ko] installed, simply run
[source, bash]
----
ko publish github.com/projectriff-samples/http-source/cmd
----

This will publish an image whose coordinates should be noted down for further use, `<image>` below.

== Using with riff
One way to use this source is to create a container out of the image
coordinates and create a core[https://projectriff.io/docs/v0.5/runtimes/core]
or knative[https://projectriff.io/docs/v0.5/runtimes/knative] deployer. Here's an example:

Assuming a "in" stream exists and has already been created:
[source, bash]
----
riff streaming stream list

riff streaming stream list
NAME     TOPIC            GATEWAY                                  PROVIDER                  CONTENT-TYPE       STATUS   AGE
in       default_in       franz-kafka-liiklus-bqgp2.default:6565   franz-kafka-provisioner   application/json   Ready    8d
----

Note the _gateway_, _topic_ and _content-type_ of the stream.

Create a container out of the image created above:
[source, bash]
----
riff container create http-source-container --image <image>
----

Create a deployer out of that container, setting the expected environment variables:
[source, bash]
----
riff core deployer creata http-source --container-ref http-source-container \
   --env OUTPUTS=<gateway>/<topic> \
   --env OUTPUT_CONTENT_TYPES=<content-type>
----

Then the source can be exposed (_e.g._ with a port-forward) and invoked with
[source, bash]
----
curl http://<host>:<port>/ -HContent-Type:<content-type> -v -d <data>
----